name: Build container with preview tag

# This action gets auto-triggered by draft_release_with_desktop_app_build.yml
#   That workflow runs upon any commit to the main branch when a higher version
#   than what was previously released
# This action builds the container according to the Dockerfile,
#   and publishes it under the 'preview' tag
# Upon approving the drafted release, another action (publish_container_with_release.yml)
#   will automatically convert this is a versioned tags & 'latest'/'stable'

on:
  repository_dispatch:
    types: [trigger-container-build]
  workflow_dispatch:
  release:
    types: [published]

env:
  IMAGE_NAME: ghcr.io/kennispunttwente/tekstanalyse_met_llm

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      preview_digest: ${{ steps.inspect.outputs.digest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push preview
        id: build
        run: |
          docker buildx build \
            --push \
            --tag ${{ env.IMAGE_NAME }}:preview \
            .

      - name: Inspect preview digest
        id: inspect
        run: |
          DIGEST=$(docker buildx imagetools inspect --raw \
            ${{ env.IMAGE_NAME }}:preview \
            | jq -r '.manifests[0].digest')
          echo "preview_digest=$DIGEST" >> $GITHUB_OUTPUT
