name: Build portable Windows app 

on:
  workflow_dispatch:           

jobs:
  win:
    runs-on: windows-latest
    env:
      R_VERSION: "4.4.2" 

    steps:
      # 1 – Checkout repo
      - uses: actions/checkout@v4

      # 2 – Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3 – R (adds Rscript & Rtools)
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}

      # 4 – Restore renv library
      - uses: r-lib/actions/setup-renv@v2

      # 5 – Python (for reticulate / gliner venv)
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # 6 – JS deps
      - name: Install npm packages
        run: npm ci

      # 7 – Build (downloads R installer, packages Electron app)
      - name: Build portable app
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8 – Zip & upload
      - name: Zip dist
        run: |
          Compress-Archive -Path dist\kwallm-text-analysis-app-win32-x64 `
                           -DestinationPath kwallm-text-analysis-app-win32-x64.zip

      - uses: actions/upload-artifact@v4
        with:
          name: kwallm-text-analysis-app-win32-x64
          path: kwallm-text-analysis-app-win32-x64.zip
