name: (2) Build preview container

# This action gets auto-triggered by prepare_release.yml;
#   That workflow runs upon any commit to the main branch, in which package.json
#   has a higher version than the version previously released on GitHub
# This action then builds the container according to the Dockerfile,
#   and publishes the image under the 'preview' tag
# The preview image can then be tested to see if it's suitable for a release
# The drafted release (made by prepare_release.yml)
#   can then be published
# Upon publishing the drafted release, another action (release_preview_container.yml)
#   will automatically promote the 'preview' image to 'latest' & also add a version
#   tag matching the release

on:
  repository_dispatch:
    types: [trigger-container-build]
  workflow_dispatch:
  release:
    types: [published]

env:
  IMAGE_NAME: ghcr.io/kennispunttwente/tekstanalyse_met_llm

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      preview_digest: ${{ steps.inspect.outputs.digest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push preview
        id: build
        run: |
          docker buildx build \
            --push \
            --tag ${{ env.IMAGE_NAME }}:preview \
            .

      - name: Inspect preview digest
        id: inspect
        run: |
          DIGEST=$(docker buildx imagetools inspect --raw \
            ${{ env.IMAGE_NAME }}:preview \
            | jq -r '.manifests[0].digest')
          echo "preview_digest=$DIGEST" >> $GITHUB_OUTPUT
