name: (4) Cleanup untagged container versions

# This action cleans up the container registry for the repo,
#   removing all untagged images

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["(3) Release preview container"]
    types:
      - completed

permissions:
  packages: write
  contents: read

jobs:
  cleanup:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Delete all untagged image versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: tekstanalyse_met_llm
          package-type: container
          owner: kennispunttwente
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
          token: ${{ secrets.GHCR_PAT }}
