name: (0) Test app

# This workflow runs the 'shinytest2' tests as defined in tests/testthat/test-shinytest2.R
# These tests verify that basic procedures in the app function
# Workflow derived from https://github.com/rstudio/shinytest2/tree/main/actions/test-app/example-test-app-description.yaml

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-app:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: "4.5.1"}

    # ── Environment ─────────────────────────────────────────────────────
    env:
      GITHUB_PAT:        ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      # 1 source code ---------------------------------------------------
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      # 2 uv ------------------------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4

      - name: Install python modules with uv
        run: uv sync

      # 2 system deps for R packages -----------------------------------
      - name: Install system dependencies for R packages
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser libfontconfig1-dev libpng-dev \
          libx11-dev libnode-dev libwebp-dev

      # 4 R toolchain ---------------------------------------------------
      - uses: r-lib/actions/setup-pandoc@bd49c52ffe281809afa6f0fecbf37483c5dd0b93
      - uses: r-lib/actions/setup-r@bd49c52ffe281809afa6f0fecbf37483c5dd0b93
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@bd49c52ffe281809afa6f0fecbf37483c5dd0b93

      # 5 run the tests -------------------------------------------------
      - uses: rstudio/shinytest2/actions/test-app@6ce71fd73f00b3d6925bc92a9a1f51eef91e3443
        with:
          app-dir: "."
